---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gtoumie/ms-config-data
          searchPaths: config
        native:
          searchLocations: classpath:offline-repository/
server:
  port: 8001